title: Software engineering handbook - prototype

org_name: Digital Health and Care Wales

#baseurl: /

plugins:
  - jekyll-redirect-from

github_editme_path: /Geoff1900/Geoff1900.github.io-handbook/edit/master/

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
