title: Open Architecture Docs

org_name: Service

#baseurl: /Geoff1900.github.io-handbook

plugins:
  - jekyll-redirect-from

github_editme_path: /nwisbeta/open-architecture/edit/master/

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
